//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCongTy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaiDangThongBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiDangThongBao()
        {
            this.PhongBan = new HashSet<PhongBan>();
        }

        public int? IDBaiDang { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tiêu đề.")]
        [StringLength(150,MinimumLength =20,ErrorMessage = "Từ 20 đến 150 kí tự")]
        public string TieuDe { get; set; }
        public string Thumbnail { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TheLoai { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual TheLoai TheLoai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongBan> PhongBan { get; set; }
    }
}
